name: jaguar_serializer_bench
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: luis <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_serializer: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
