name: dson_bench
description: A web app that uses DSON
version: 0.0.1
#homepage: https://www.example.com
#author: luis <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  dson: ^0.6.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
